version: 2

sources:
  - name: demo_data
    database: RAW
    schema: TPCH_SF001

    tables:
      - name: customer
        description: main customer table
        columns:
          - name: c_custkey
            description: unique customer key
            tests:
              - unique:
                  severity: warn
              - not_null:
                  severity: warn
          - name: c_name
            description: customer id
          - name: c_address
            description: address of the customer
          - name: c_nationkey
            description: foreign key to stg_tpch_nations

      - name: lineitem
      - name: nation
      
      - name: orders
        description: main order tracking table
        freshness: # make this a warning as this is static data
          warn_after: {count: 6, period: hour}
          # error_after: {count: 12, period: hour}
        loaded_at_field: o_orderdate::timestamp
